puremourning/vimspector

- azure-pipelines.yml
- run_tests
rather than only in CI. This means you just ./run_tests to run them locally.
> run_tests should build the test programs

- python3/vimspector/debug_session.py
- python3/vimspector/utils.py
- tests/testdata/cpp/simple/.vimspector.json
This allows a configuration variable to reference, say `${workspaceRoot}`, e.g.:
```
"configurations": {
"python - launch nosetests": {
"adapter": "vscode-python",
"variables": {
"python_path": {
"shell": [
"python",
"${workspaceRoot}/run_tests.py",
"--dump-path"
]
}
},
```
> Allow variables to reference other variables in other layers

- autoload/vimspector/internal/channel.vim
Fixes #55 
The `channel` based servers were broken in the refactor of the closedown sequence. 
We now call `OnServerExit` from the channel close callback, and also call that manually from the `StopDebugSession` method. Note: `close_cb` is _not_ called when closing a channel using `ch_close` hence we have to call it manually in that case.
@peanutbutterspice
> Fix shutdown sequence for channel-based servers

- python3/vimspector/breakpoints.py
- python3/vimspector/debug_session.py
- python3/vimspector/utils.py
- support/test/python/simple_python/main.py
There are 2 things we ask for input for:
- input variables
- exception breakpoint filters
It's irritating to have to repeat yourself when going through the
edit/debug loop.
Howver, cacheing has some quirks and disadvantages - they key one being
when to clear the cache. To resolve this we take two slightly different
approaches:
1. For input variables, we remember the choice of the user, but present
that only as the default, so they can just hit enter to accept it. We
already rememeber the choices for the length of the debug session (i.e.
across 'restart' calls).
2. For exception breakpoints, we remember the choices for as long as the
current session is running.
This allows users to hit the 'restart' button without being prompted at
all.
Meanwhile, we also remove the (broken) support for …
> Remember user choices

- README.md
- install_gadget.py
- python3/vimspector/code.py
- python3/vimspector/stack_trace.py
- python3/vimspector/variables.py
- support/test/chrome/.tern-project
- support/test/chrome/.vimspector.json
- support/test/chrome/www/index.html
- support/test/chrome/www/js/test.js
This allows using vim to debug client code running in chrome, assuming that's a thing you might want to do.
It also irons out a couple of bugs and works around a protocol violation in that server.
> Add chrome debugger

- azure-pipelines.yml
- install_gadget.py
- tests/ci/image/Dockerfile
Fixes #65 
* Fix argument name `--force-enable-chrome` rather than `--force-enable-typescript`
* Fix extract of some packages which are `vsix.gz` rather than `tar.gz` (this is actually gzip'd zip!)
* Fix some python2/3 incompatibilities with running `node`
TODO: would like to add running `install_gadget.py` using both python 2 and 3 to the CI.
> Fix installation issues

- python3/vimspector/stack_trace.py
- python3/vimspector/utils.py
`lldb-vscode` can be used directly from vimspector, but it requires the use of `sourceReference` as its break on start is really on start deep in the library.
It turns out that the use of the `source` request and `sourceReference` is actually not optional in the spec. Our solution is simple enough: request when jumping to a frame. 
Yet more cringy race conditions and hacky async requests in this PR, but the result is quiet satisfying:
Haven't tried the other adapters yet.
> Source request

- .ycm_extra_conf.py
- docs/CONFIGURATION.md
- docs/index.md
- docs/schema/gadgets.schema.json
- docs/schema/index.md
- docs/schema/vimspector.schema.json
- python3/vimspector/breakpoints.py
- python3/vimspector/debug_session.py
- python3/vimspector/install.py
- python3/vimspector/utils.py
- tests/testdata/cpp/simple/.vimspector.json
* Find the vimspector config based on the dir of the file not working dir of the editor
* Set up exception breakpoints in vimspector config (#53)
* Allow user-configuration of gadgets in the gadgetDir (using `.gadgets.d`). These override the ones written by `install_gadget.py`
* Allow gadget config to specify defaults for debug launch `configuration` - this allows to set, for example, the `miDebuggerPath` once
* Full documentation of the config and a JSON schema (#11)
> [READY]: Document config format and add some usability improvements

- docs/configuration.md
- python3/vimspector/breakpoints.py
- run_tests
- support/test/python/simple_python/.vimspector.json
- tests/breakpoints.test.vim
- tests/language_python.test.vim
- tests/lib/autoload/vimspector/test/setup.vim
Fixes #63 
If signs are moved by user actions, use the current lnum of the sign for the breakpoint.
> Fix issues with breakpoints not being in the correct location

- install_gadget.py
- python3/vimspector/code.py
- python3/vimspector/debug_session.py
- python3/vimspector/utils.py
- python3/vimspector/variables.py
This enabled syntax highlighting for locals window and watches window. This just aids readability a little. It always uses the syntax of the "code" window, whatever that happens to be.
> Syntax highlighting for locals and watches

- README.md
Currently unsupported for technical reasons, not philosophical ones.
> Make statement about neovim support

- README.md
Thank you for this project!
After trying this out, I couldn't figure out how to return close the debugger, which turned out to be pretty simple. I suggest to document it as a part of a regular debugging flow.
This PR also includes a couple of other fixes to readme.
> Document closing the debugger

- install_gadget.py
Run git commands in the right repo
Fixes #78
> Fix node dap installation when run outside of a git repo

- autoload/vimspector/internal/balloon.vim
- python3/vimspector/debug_session.py
- python3/vimspector/variables.py
Remove the ... balloon in non code windows
Problem: In non-code window, user see a '...' balloon even if python knows it does not need to work
Solution: use `pyeval` in vim so that python's knowledge is getting back from the stack as return value
> Fix: Remove balloon '...' in windows != code_window

- .ycm_extra_conf.py
- install_gadget.py
- python3/vimspector/breakpoints.py
- python3/vimspector/debug_session.py
- python3/vimspector/output.py
- python3/vimspector/stack_trace.py
- python3/vimspector/utils.py
- python3/vimspector/variables.py
* Allow arbitrary ssh arguments, such as specifying a key, or other options
* Fix `frame` being optional 
* Fix go which sometimes fails to work when setting breakpoints in advance
* Fix some issues when servers don't provide `source` or `line` (looking at you java)
* Expand vars in vars. This allows more composition of config.
* Fix true/false when in adapter config's configuration defaults (i.e. don't use json.dumps, use a global)
> A selection of misc fixes and enhancements from ongoing usage

- python3/vimspector/debug_session.py
- python3/vimspector/utils.py
Fixing  #83:  Silencing the message with early return from function and little echo warning
__Note:__ I encapsulated the check in a function decorator: This may seem overkill but at first I did not and ended with :
```python
def StepOver( self ):
if (not self._connection
and utils.MessageNoConnection( )
or self._stackTraceView.GetCurrentThreadId() is None):
return
...
```
```python
@utils.IfConnected
def StepOver( self ):
if self._stackTraceView.GetCurrentThreadId() is None:
return
...
```
As many functions need the check, for readability and avoiding boolean magic, I preferred the second.
PS: I didn't already say, so my groupie's turn:
@puremourning your plugin is awesome !
1. Finally a debugger on vim (of course thk microsoft too)
2. Very well written
1. __code:__ small functions, …
> Check connection before some operation (`next`) to avoid Python errors in vim messages

- README.md
Fixes #29 
* Remove `bindeval`: Instead, require a send function in the job/channel API, and marshal the arguments through global variables.
* Abstract terminal API
* Abstract job API
TODO:
Might decide nvim is "best effort" basis only. If not, will need to:
Known issues:
But, here's vimspector "working" in neovim:
[![asciicast](https://asciinema.org/a/73kkZlqrUhPRxjgx0QWMKBr0A.svg)](https://asciinema.org/a/73kkZlqrUhPRxjgx0QWMKBr0A)
> Support neovim

- README.md
- install_gadget.py
This sort-of fixes macOS issues when used with my lldb-mi.
> upgrade cpptools to 0.26.3

- README.md
- install_gadget.py
Thanks for #77 
I've added support for php via felixfbecker/vscode-php-debug and so far everything works beautifully like in vscode.
Also here is a ported debugger configuration based on https://github.com/felixfbecker/vscode-php-debug/blob/c7280b6ea87b4ee0010ddb9821994164e08cac95/package.json#L240-L255
`PATH_TO_PROJECT_DIR/.vimspector.json`:
```json
{
"$schema": "https://raw.githubusercontent.com/puremourning/vimspector/master/docs/schema/vimspector.schema.json",
"configurations": {
"Listen for XDebug": {
"adapter": "vscode-php-debug",
"configuration": {
"name": "Listen for XDebug",
"type": "php",
"request": "launch",
"port": 9000,
"stopOnEntry": false,
"pathMappings": {
"/var/www/html": "PATH_TO_PROJECT_DIR"
}
}
},
"Launch currently open script": {
"adapter": "vscode-php-debug", …
```
> add debug adapter for php (based on felixfbecker/vscode-php-debug)

- azure-pipelines.yml
- install_gadget.py
- tests/testdata/cpp/simple/.vimspector.json
Let's see what azure thinks. We know cpptools is broken in 10.15.
> Switch to macOS 10.14 in CI (10.13 will be disabled soon)

- .github/ISSUE_TEMPLATE/bug_report.md
- CONTRIBUTING.md
- autoload/vimspector/internal/state.vim
Import the vim module
In Vim, the vim module is always imported by magic in the global scope,
but the docs suggest that you're supposed to import it anyway.
In NeoVim it's never imported so we were relying on some other plugins
having already imported it.
Fixes #101
> Import vim

- python3/vimspector/debug_session.py
- support/test/example/attach.vim
- support/test/example/cpp.json
This allows things like PID to connect to to be specified directly in the launch options, e.g. from `LaunchWithSettings` and/or by using a `variables` block and running a `shell` command.
Include an example of how you might make a command line script to launch directly into vimspector with `vim -S script.vim`.
Loosely related to #97 
Fixes some issue with #85
> Improve workflow for launching vimspector from scripts

- .gitignore
- install_gadget.py
Hi @puremourning! 
First of all, thank you so much for the plugin! Man, is it awesome! I thing I had never realized how much struggle it had been to use all kinds of different debuggers (we code in like 5 languages simultaneously)!
This pr is a tiny contribution that might help unfortunate people like myself to bypass the insanity of the certificate chanis that our IT had installed, and which neither JVM (fixed that with some sweat and tears) nor python (no luck after a day of bashing my head against the display) can verify.
Basically, it adds a "--no-ssl" flag which switches off the certificate validation. This helps bypass the self-signed certificates in the chains (in any case, we are downloading from MS's git repo).
I will be more than happy if you choose to accept this pr. Thanks in …
> Add a --no-ssl flag that switches off certificate verification

- README.md
- autoload/vimspector/internal/neojob.vim
- autoload/vimspector/internal/neoterm.vim
Implement the 'env' option properly(!?) for neovim. Copy and update the _global_ environment when calling `jobstart` and `termopen`.
This makes `debugpy` work in neovim (and possibly some other stuff).
Fun times.
cc @oblitum @BlueDrink9
references #105
> Support setting environment in neovim

- README.md
Fixes the broken link in README. Reference-style links use square brackets.
> README referenced link typo

- .vintrc.yml
- .ycm_extra_conf.py
- CONTRIBUTING.md
- README.md
- azure-pipelines.yml
- dev_requirements.txt
- install_gadget.py
- python3/vimspector/breakpoints.py
- python3/vimspector/debug_session.py
- python3/vimspector/output.py
- python3/vimspector/utils.py
- support/test/python/simple_python/.vimspector.json
- tests/breakpoints.test.vim
- tests/language_python.test.vim
- tests/lib/plugin/screendump.vim
- tests/lib/plugin/shared.vim
- tests/lib/run_test.vim
- tests/tabpage.test.vim
Thanks to @int19h for all the help, we're now forcing migration to `debugpy`; the old adapter is still there (for now) but requires specifying `--force-enable-python.legacy` to `install.py`. Now `--enable-python` will locally build `debugpy` in the gadget directory (rather than relying on pip or any of that nonesense). 
Fixes #109
> Switch to debugpy rather than vscode-python

- README.md
- autoload/vimspector/internal/job.vim
- autoload/vimspector/internal/neojob.vim
- autoload/vimspector/internal/neoterm.vim
- install_gadget.py
- python3/vimspector/debug_session.py
- python3/vimspector/installer.py
- python3/vimspector/output.py
- python3/vimspector/utils.py
Little was required to make basic support:
* Fix some installer path handling
* Fix some tracebacks when servers die almost immediately
I have done only minimal testing using the python (debugy) debugger.
Fixes #74 
Limitations:
* the 'file tail' functionality doesn't work as it relies on `tail`. so you can't view the log files in the output window. that's a big bummer, and my experience with documenting the deficiencies of neovim has been that nobody pays attention to the documentation.
> Experimental Windows support

- README.md
- azure-pipelines.yml
- docs/configuration.md
- install_gadget.py
- python3/vimspector/debug_session.py
- python3/vimspector/installer.py
- python3/vimspector/vendor/json_minify.py
- run_tests
- support/test/python/simple_python/.vimspector.json
- tox.ini
Debate rages about whether JSON should have comments. The specification
says it shouldn't but the author of JSON suggested that if you want to
use JSON for configuration, then pipe it through jsmin before parsing.
So that's what we do, using a tiny JSON minifier from
https://github.com/getify/JSON.minify/tree/python
Closes #135
> Support c-style comments in JSON

- README.md
- autoload/vimspector/internal/neopopup.vim
- autoload/vimspector/internal/popup.vim
- python3/vimspector/debug_session.py
- python3/vimspector/utils.py
- tests/ci/image/Dockerfile
- tests/tabpage.test.vim
Sometimes it can take quite a while to start up and initialise the debug
adapter. So we use popup/float to display the status as we start up and
shut down.
This increases minimum Vim version to 8.2, but that's been out for ages
now and I intend to agressively require latest/later vim/neovim
versions.
> Add a splash popup while starting up

- python3/vimspector/code.py
- python3/vimspector/debug_session.py
`:tabnew` creates a new buffer. Use `tabedit %`
Fixes #138 
@ckipp01 can you try it ?
> Don't create a new buffer when opening the vimspector tab

- install_gadget.py
vscode-cpptools upstream recently had a fix which makes the workarounds described in the README unnecessary (debugging now works again in Catalina without the need for CodeLLDB).
This pull request changes `install_gadget.py` to have it fetch the newest version `0.27.0` to bring these changes into the debug adapter vimspector uses.
The checksums were generated by downloading the latest version and running `shasum -a 256 <filename`. I can confirm that this works on macOS Catalina 10.15.3, and resolves #146.
> Bump version of vscode-cpptools from 0.26.3 to 0.27.0

- README.md
- autoload/vimspector.vim
- plugin/vimspector.vim
- python3/vimspector/breakpoints.py
- python3/vimspector/debug_session.py
This is the minimal required for a user to use conditional breakpoint -
we add an options dict to each breakpoint (line and function) and allow
the condition to be supplied. We add a plug mapping and a default
shortcut (<leader><F9>) to add one where we ask the user to enter the
condition and hit expression. This isn't great but it works.
We don't check the capabilities, so they would just be ignored if used
on a server that doesn't support them. We also ask for a hit expression
which most users won't understand so this isn't ideal either.
No tests, and no documentation yet.
Added a new sign type too, so you can see where a breakpoint is conditional.
I actually use this:
```
" vimspector
let g:vimspector_enable_mappings = 'HUMAN'
sign define vimspectorBP text=🔴         texthl=Normal
sign …
```
> Add basic support for conditional breakpoints

- CONTRIBUTING.md
- install_gadget.py
- python3/vimspector/debug_session.py
- python3/vimspector/install.py
- python3/vimspector/utils.py
- run_tests
- tests/tabpage.test.vim
This is handy for running the tests in a clean way (e.g. if you have a configurations directory or custom gadgets, etc.)
It could also be useful in multi-user environments and/or (unfortunately) for third-party packaging (which I _strongly_ discourage)
> Allow moving the gadget/configuration dirs to arbitrary location

- README.md
I got tripped up getting started because the documentation incorrectly uses `vimspector.json` and I was getting an error about no debug configurations found.
> Fix incorrect naming of `.viminspector.json`

- install_gadget.py
As mentioned here: https://github.com/puremourning/vimspector/issues/141#issuecomment-605289072
> Disable subprocess debugging by default in debugpy

- support/test/go/hello_world/.vimspector.json
Refer to https://github.com/puremourning/vimspector/issues/178 for more info. Tested with Go 1.12 and Go 1.14
> [#178]Set GO111MODULE to off and the sample project won't fail in go 1.12+

- README.md
- install_gadget.py
- support/test/cpp/simple_c_program/.vimspector.json
cc @MintSoup
add a way for the installer to set up different adapters by OS.
Add some guidance to the readme.
Rationalise the "demo" cpp app
Fixes #129
> Windows support for cpptools

- autoload/vimspector/internal/channel.vim
- autoload/vimspector/internal/job.vim
- autoload/vimspector/internal/neochannel.vim
- autoload/vimspector/internal/neojob.vim
- autoload/vimspector/internal/neoterm.vim
- python3/vimspector/code.py
- python3/vimspector/debug_session.py
- python3/vimspector/output.py
- python3/vimspector/stack_trace.py
- python3/vimspector/utils.py
- python3/vimspector/variables.py
- support/test/java/test_project/.vimspector.json
- support/test/java/test_project/java.vim
- support/test/java/test_project/pom.xml
- support/test/java/test_project/src/main/java/com/vimspector/test/Base.java
- support/test/java/test_project/src/main/java/com/vimspector/test/TestApplication.java
There are a few things that we have to do:
* Try to stop using `vim.Window` objects as much as possible. We can do this completely for variables and stack trace. You can even re-open them by `:bu vimspector.Watches`
* For the output window, it's tricker as this is a 'quasi-tab-window'. If it's closed `vim.Window.valid` goes `False` so just check that in all the places we need it
* Tidy more shutdown races - we can receive data for a _new_ connection after an Exit callback, so check taht the channel we got is associated with the _current_ job.
* Fix the terminal spam on exit - never try to use python in a callback if `v:exiting isnot# null` per https://github.com/neovim/neovim/issues/11725
* Fix a regression introduced by a fix. We now correctly try and shut down jobs in the output views …
> Allow users to close UI windows

- install_gadget.py
- python3/vimspector/variables.py
I was running into an issue when debugging on Windows where any each step there would be a KeyError when trying to find any non-expensive scope. I was able to fix it with a quick change. I have only tested this with C# on Windows
> No longer throws a KeyError when checking for non expensive scope

- .gitignore
- autoload/vimspector/internal/neojob.vim
- python3/vimspector/code.py
- python3/vimspector/debug_session.py
- python3/vimspector/stack_trace.py
- python3/vimspector/utils.py
- python3/vimspector/variables.py
- support/test/java/test_project/src/main/java/com/vimspector/test/Base.java
- support/test/java/test_project/src/main/java/com/vimspector/test/TestApplication.java
- support/test/java/test_project/src/main/java/com/vimspector/test/TestGeneric.java
c6e8e80 (HEAD -> bugfixes) Remove hard-coded terminal width which doesn't work on smaller width screens
a4f3fd9 Disable relativenumber in utility windows; disable textwidth in neovim too
2440a98 (origin/bugfixes) Tidy unknwon types and values
434a6f4 Only expand one cheap scope by default - don't keep others expanded from previous frames
fc7725f Only expand one inexpensive scope; codeLLDB lies about how expensive things are
0938d72 Re-use a window if we can, as it's more efficient; don't wipe out the generated code buffers in case the code window gets used for temporary buffer switch
8d2ea44 Make Restart and Stop work properly (and together)
97a5d73 Ignore venv and test basedir
b3c86bc Use the original java test code
These are a rollup of issues found while testing the ui-custom branch. …
> A number of Bugfixes

- install_gadget.py
- python3/vimspector/gadgets.py
- python3/vimspector/install.py
- python3/vimspector/installer.py
- syntax/vimspector-installer.vim
This adds a --upgrade option to install_gadget.py and makes
VimspectorUpdate only update things which have changed.
To do this, we record the gadget spec in a manfiest file and compare it
with the current spec when in upgrade mode.
'Changed' in this case means that the gadget spec has changed from the
last time the installer was run. It does _not_ actually check the
presence of the gadget.
--
Also update the node debugger to the latest version and remove the node 10 check :) 
Fixes #176 
Fixes #217
> Upgrade gadgets when they change

- autoload/vimspector.vim
- docs/configuration.md
- docs/custom_gadget_file.md
- plugin/vimspector.vim
- python3/vimspector/breakpoints.py
- python3/vimspector/code.py
- python3/vimspector/developer.py
- python3/vimspector/utils.py
- python3/vimspector/variables.py
- run_tests
- support/test/python/simple_python/.vimspector.json
We want to be able to use `${Variable:default value goes here}`, but the built-in python template strings won't let us.
So looking at the standard library code, most of it is cruft we don't need. We can just pick and choose the code we want and re-implement, adding the syntax elements as we need them.
> Add ability to specify defaults for variables

- python3/vimspector/utils.py
- support/test/python/simple_python/.vimspector.json
Initially I considered using #i, #s, etc. to coerce to specific types,
but then it wasn't clear of the semantics (particularly for bool, where
JSON bool true/false, Python bool True/False).
But it turns out that we can just coerce any key from a JSON string.
Users can _probably_ type JSON strings for most things, or use variables
to run scripts to generate them, this allows essentially complete
flexibility to define the data types needed to populate the launch spec.
The purpose of this is to allow some level of automated setup by
requesting data from the user and then (subsequently) saving the
flattneed config to the vimspector config file.
TODO:
This is stage 1 in providing better support for initial setups and guided or automated setup.
> Ability to coerce types in the vimspector config

- python3/vimspector/breakpoints.py
- python3/vimspector/utils.py
Neovim does not raise:
* KeyError when accessing a vim dict
* KeyboardInterrupt when ctrl-c at a prompt
Instead it raises some internal subclass of vim.errro which cannot
easily be identified, so we just catch any vim.error.
Fixes #236
> Fix neovim (again) - incompatible exception behaviour

- python3/vimspector/utils.py
Fixed an issue where `...` kept showing up in the balloon.
Before:
After:
No information was displayed in the balloon view.
It kept showing `...` was displayed.
Solution: call `balloon_show("")` once and remove the `...` balloon.
1. Run `gvim.exe -Nu mini_vimrc main.py` (`/support/test/python/simple_python/main.py`)
```
" min_vimrc
set encoding=utf-8
scriptencoding utf-8
syntax enable
filetype plugin indent on
set nocompatible
set ambiwidth=double
set runtimepath^=~\ghq\github.com\puremourning\vimspector
nmap <F5> <Plug>VimspectorContinue
nmap <C-m> <Plug>VimspectorToggleBreakpoint
colorscheme murphy
language messages en
```
1. Put the breakpoint on line 15.
2. Press `<F5>`. (Start)
3. Place the cursor on the variable B. (Balloon Display)
4. `...` is displayed and continues.
Use the …
> Fix balloon display

- README.md
- compiler/vimspector_test.vim
- python3/vimspector/breakpoints.py
- python3/vimspector/code.py
- python3/vimspector/settings.py
- python3/vimspector/signs.py
- python3/vimspector/utils.py
- support/custom_ui_vimrc
- tests/breakpoints.test.vim
- tests/language_go.test.vim
- tests/language_python.test.vim
- tests/lib/autoload/vimspector/test/signs.vim
Too many plugins use the default priority of 10 so they race/chase.
Allow uses to configure the priorities and make sure that the defaults
are documented.
Fixes #231
> Allow customisation of the signs

- python3/vimspector/output.py
- tests/tabpage.test.vim
We create a new window for the output view, then we use _CreateBuffer to create some buffers. This leaks the empty buffer that gets put in the output view.
This solution re-uses that empty buffer for the first output buffer created.
TODO:
> Don't leak buffers when creating output view

- README.md
- python3/vimspector/breakpoints.py
- python3/vimspector/code.py
- python3/vimspector/debug_session.py
- python3/vimspector/installer.py
- python3/vimspector/settings.py
- python3/vimspector/signs.py
- python3/vimspector/utils.py
- tests/breakpoints.test.vim
- tests/tabpage.test.vim
Also, set the priority to > 100 as required in https://github.com/vim/vim/commit/39f7aa3c3124065b50f182b1d2f7ac92a0918656
This shows just a subtle highlight by default, but you can customise to use e.g. `debugPC` if you like.
Also centralise all the settings because they were getting out off hand.
> Highlight the current line using linehl=CursorLine

- README.md
- autoload/vimspector.vim
- autoload/vimspector/internal/neopopup.vim
- python3/vimspector/debug_session.py
- python3/vimspector/gadgets.py
- python3/vimspector/output.py
- python3/vimspector/utils.py
- python3/vimspector/variables.py
- support/test/bash/test_script
- support/test/chrome/run_server
- support/test/chrome/www/js/test.js
- support/test/node/simple/simple.js
- tests/tabpage.test.vim
Add omnifunc for prompt buffers
This synchronous completion can be used with any completion system
including built-in CTRL-X CTRL-O.
The filetype of the prompt buffers is set to VimspectorPrompt so that it
can be identified by completion systems. For example, this works well
with YCM:
let g:ycm_semantic_triggers =  {
\   'VimspectorPrompt': [ '.', '->', ':', '<' ]
\ }
closes #245 
TODO:
> Support completion for console and watches.

- README.md
- python3/vimspector/code.py
- python3/vimspector/settings.py
- tests/breakpoints.test.vim
- tests/lib/autoload/vimspector/test/signs.vim
Vim only renders a single sign-per-line. If we have the PC _and_ a
breakpoint, we should make that clear. Do this using a vimspectorPCBP
sign which combines both vimspectorPC and vimspectorBP (sort of).
We can't (unfortuantely) render the breakpoint blob in a different
colour, but it's at least obvious when we toggle on the PC line.
Fixes #257
> Display a different sign when there's a breakpoint on the PC line

- python3/vimspector/breakpoints.py
- python3/vimspector/code.py
- python3/vimspector/debug_session.py
- python3/vimspector/signs.py
- python3/vimspector/terminal.py
- python3/vimspector/utils.py
- tests/breakpoints_doublewidth.test.vim
* Launch remote commands in a terminal window. this makes actually seeing the debuggee output possible (as if runInTerminal was used) and allows for remove launches to accepts standard input.
Additionally a few minor fixes:
* Fix variable defaults when the var name contains underscores
* Fix ambiwidth again (fixes #263 )
> Launch remote commands in the terminal

- autoload/vimspector.vim
- python3/vimspector/code.py
- python3/vimspector/debug_session.py
- python3/vimspector/output.py
- tests/testdata/cpp/simple/.vimspector.json
- tests/variables.test.vim
Few problems:
- we were passing a dict instead of a list of breakpoints
- if the breakpoint had a source which was {} we crashed (even though this is clearly a break of the spec)
- we didn't support the 'removed' event
Fixes #278
> Fix breakpoint event

- python3/vimspector/gadgets.py
As of June 2020, the new home of vscode-go is https://github.com/golang/vscode-go.
> vscode-go: Update plugin and use new repository address.

- README.md
- autoload/vimspector.vim
- plugin/vimspector.vim
- python3/vimspector/breakpoints.py
- python3/vimspector/code.py
- python3/vimspector/debug_session.py
- python3/vimspector/signs.py
- python3/vimspector/stack_trace.py
- python3/vimspector/utils.py
- support/test/python/simple_python/.vimspector.json
- support/test/python/simple_python/make_env.sh
- support/test/python/simple_python/print_env.py
- tests/breakpoints.test.vim
- tests/breakpoints_doublewidth.test.vim
- tests/language_go.test.vim
- tests/lib/autoload/vimspector/test/signs.vim
- tests/mappings.test.vim
- tests/temporary_breakpoints.test.vim
- tests/testdata/cpp/simple/.vimspector.json
Introduce temporary breakpoints, allowing for "run to cursor", which is occasionally more convinient than F9,F5,F9
> Run to cursor

- .github/workflows/build.yaml
- .gitignore
- README.md
- python3/vimspector/gadgets.py
- python3/vimspector/installer.py
- support/test/lua/love-headless/.vimspector.json
- support/test/lua/love-headless/conf.lua
- support/test/lua/love-headless/main.lua
- support/test/lua/love/.vimspector.json
- support/test/lua/love/main.lua
- support/test/lua/simple/.vimspector.json
- support/test/lua/simple/simple.lua
- tests/ci/image/Dockerfile
- tests/language_lua.test.vim
Add the lua adapter to gadgets.py and installer.py, update the README.md file and create basic tests using lua, luajit and love.
I tested installing the lua debugger with both install_gadget.py and VimspectorInstall and tested debugging in both test cases added to support/test/lua.
I decided to add it as Supported and set `'enabled': False` in `gadgets.py`. If I'm wrong just tell me and I'll change it.
> Add lua support through local-lua-debugger-vscode

- python3/vimspector/code.py
- python3/vimspector/output.py
- python3/vimspector/utils.py
- python3/vimspector/variables.py
https://github.com/neovim/neovim/issues/12689
don't create the winbar if the vim emulator is neovim. it seems to not know how to render if you create a menu named `WinBar.<anything>`
Too many people are using neovim "0.5" and experiencing horrible UI to wait for it to be fixed, so we work around it.
Fixes #300
> Work around neovim WinBar rendering bug

- README.md
- autoload/vimspector.vim
- autoload/vimspector/internal/state.vim
- python3/vimspector/code.py
- python3/vimspector/debug_session.py
- python3/vimspector/settings.py
- python3/vimspector/stack_trace.py
- run_tests
- support/test/node/simple/simple.js
- tests/breakpoints.test.vim
- tests/breakpoints_doublewidth.test.vim
- tests/ci/image/Dockerfile
- tests/lib/plugin/shared.vim
- tests/stack_trace.test.vim
- tests/testdata/cpp/simple/.gitignore
- tests/testdata/cpp/simple/.ycm_extra_conf.py
- tests/testdata/cpp/simple/Makefile
- tests/testdata/cpp/simple/threads.cpp
- tests/variables.test.vim
Fixes #285 
Specification:
> Whenever the generic debugger receives a stopped or a thread event, the development tool requests all threads that exist at that point in time. Thread events are optional, but a debug adapter can send them to force the development tool to update the threads UI dynamically even when not in a stopped state. If a debug adapter decides not to emit Thread events, the thread UI in the development tool will only update if a stopped event is received.
> After a successful launch or attach, the development tool requests the baseline of currently existing threads with the threads request and then starts to listen for thread events to detect new or terminated threads. Even if a debug adapter does not support multiple threads, it must implement the threads request and …
> [WIP] Improve Threads Handling

- support/test/lua/love-headless/.vimspector.json
- support/test/lua/love/.vimspector.json
- support/test/lua/simple/.vimspector.json
- support/test/lua/simple/simple.lua
- tests/language_lua.test.vim
Change lua test files to call `require 'lldebugger'` only when using love, because it's not needed with lua or luajit. Also add `stopOnEntry` key to test `.vimspector.json` because it works correctly with this change.
Did this change after talking to the developer of local-lua-debugger-vscode about stopOnEntry not working correctly and it turned out my configuration was wrong and it actually works. Changed all relevant files here to reflect the correct usage.
> Improve lua configuration and test files

- python3/vimspector/debug_session.py
- support/test/cpp/simple_c_program/.vimspector.json
- support/test/cpp/simple_c_program/test_c.cpp
- support/test/python/simple_python/.vimspector.json
- support/test/python/simple_python/run_with_debugpy
This causes problems on windows, and is wasteful anyway. The subprocess
will pick up the environment from its parent.
Fixes #310
Closes #311 
@zoumi can you try this patch ? I took your idea and extended it for all platforms. This seems to work on macOS at least.
> Don't copy the environment to update it

- docs/configuration.md
- docs/schema/vimspector.schema.json
- python3/vimspector/debug_session.py
- support/test/python/simple_python/.vimspector.json
- support/test/python/simple_python/Dockerfile
- support/test/python/simple_python/build-container
The example was was using 'launchCommand' which is not valid according
to the schema; it should be 'runCommand'.
But also, it never really worked. Vimspector would start the "adapter"
(in this case, try and connect to the TCP port) before running the
"prepare" commands, wich in this case would actually start debugpy
listening. So to solve that we run the prepare commands earlier.
Hopefully this won't cause a regression for Java and C++ remote attach,
which we don't really have tests for.
Finally, due to the way docker works, when you forward a port and
nothing is listening on it, docker _accepts_ the connection then
immediately drops it. This is _super_ annoying meaning that it looks to
vimspector liek the server instantly dies if it takes nonzero time for
the remote commands to open the …
> Fix docker example

- python3/vimspector/gadgets.py
1.2.1 is, as of this commit, the most recent version of the gadget.
The version currently used, 1.0.0b12 is not compatible with Python 3.9:
the build errors out on missing arguments for _PyEval_EvalFrameDefault.
Python 3.9 is the version of Python that will be shipped with the
upcoming debian release.
Support for 3.9 was merged in before the final 1.0.0 version. So,
upgrading the gadget will bring in python 3.9 support
> bump debugpy gadget to version 1.2.1

- python3/vimspector/stack_trace.py
- support/test/tcl/test
Fixes #333 
Fix thread state and PC for starting node app
The problem is the sequence of events sent by the debug adapter.
Vimspector requests threads:
* When the initialisation exchange completes (requests all threads)
* Whenever a thread event is received
* whenever a stopped event is received.
If any of those happens while any other request is in progress, we cache
the request and handle it later. The latest request is processed when
the response to the outstanding request is received.
The problem is if the event is a stopped event, it is the handling of
the threads request that actually sets the thread state internally to
stopped. In a sequence where the first event is a stopped event, we end
up discarding the stopped event. like:
1. Stopped event (thread 1 = stopped) (request …
> Fix node thread

- python3/vimspector/utils.py
- tests/lib/run_test.vim
- tests/python/Test_ExpandReferencesInDict.py
- tests/utils.test.vim
The problem was that the python regex engine is strictly left-to-right,
so matching `[^}]|\\}` against \\}} meant that the `\\` was consumed by
the left of the `|`. The solution is to just switch them around.
Also add a way to run python tests from within vim, so we can actually
test this stuff.
Fixes #340
> Fix variable substitution for multiple defaulted vars

- python3/vimspector/gadgets.py
Update vscode-php-debug to 1.14.9, it works for bothe Xdebug 2/3.
I also checked documents, it seems no need to update.
> Update vscode-php-debug to 1.14.9, it works for both Xdebug 2/3

- README.md
- autoload/vimspector.vim
- plugin/vimspector.vim
- python3/vimspector/debug_session.py
- python3/vimspector/stack_trace.py
CodeLLDB seems to actually support the terminateDebugee flag, so rather
than just forcefully killing things, ask the user if they want to.
Fixes #353
> Ask the user about terminating the debuggee

- autoload/vimspector.vim
- plugin/vimspector.vim
- tests/variables.test.vim
I looked for a test to cargo cult, but I couldn't find any place where
`:VimspectorWatch` was called with no args and fed a string to the
`input()` call.
I also looked at the commit that added the same behavior for
VimspectorWatch (4586aa36) and it included no tests. If there's an easy
way to test this, please let me know.
> Allow zero or one args for :VimspectorEval (like :VimspectorWatch)

- README.md
- autoload/vimspector.vim
- autoload/vimspector/internal/balloon.vim
- plugin/vimspector.vim
- python3/vimspector/debug_session.py
- python3/vimspector/output.py
- python3/vimspector/settings.py
- python3/vimspector/stack_trace.py
- python3/vimspector/utils.py
- python3/vimspector/variables.py
- support/custom_ui_vimrc
- tests/variables.test.vim
Use ctrl-enter on a variable to set its value.
Unfortunately ctrl-enter only works if you have working `modifyOtherKeys` set up (and afaict doesn't work in neovim).
So we add a surreptitious way to modify the mappings through configuration. This is currently undocumented however, as I'm not sure how far we want to expose it. There are some serious issues with it (like the popup filter having to kinda try to parse the mapping spec to see if the current "key" matches it...).
But the functionality is pretty sweet, and includes command-line completion for expression (even though I'm not sure that it's actually an expression in DAP)
I should really write some tests...
> Set variable value 

- .github/ISSUE_TEMPLATE/bug_report.md
- CONTRIBUTING.md
- python3/vimspector/debug_session.py
- python3/vimspector/settings.py
- python3/vimspector/terminal.py
- tests/lib/autoload/vimspector/test/setup.vim
- tests/ui.test.vim
The vimspector UI is "optimised" for wider screens with the utility windows on the left and the code on the right with a vertical split for the terminal.
however, if the window is narrow, this isn't ideal.
Add vertical (i.e. narrow) layout
This puts the 3 utility windows at the top, horizontally split, with the
code view below.  The terminal window is drawn either vertically split
(if there's room) or horizontally split otherwise.  The output window
remains at tht bottom.
We add equivalent sizing options too, setting some defauts that roughly
work on my macbook pro.
By default we switch to the narrow layout if there are fewer than 160
columns, but this can be overridden by setting g:vimspector_ui_mode.
Auto mode tries to guess the best layout, but can also be controlled with options.
> Narrow UI mode

- python3/vimspector/utils.py
- tests/python/Test_ExpandReferencesInDict.py
Previously it would default to the `${whatever}`; I think this was broken when the calculus was introduced.
> Fix default variable values having substitutions from the calculus

- python3/vimspector/gadgets.py
Simple pull to update netcoredbg to 1.2.0-738. 
**There is currently no new binary for macos, so I was hoping that setting 'version' on the macos settings would override the 'all' settings.** Please advise if that is not the case. I do not have a mac to test on.
I have tested on arch linux with kernel 5.11.4-arch1-1 and Windows 10.
> Update netcoredbg to 1.2.0-738 to support async/await

- python3/vimspector/gadgets.py
This is related to #371, which updated netcoredbg which fixed a bug with C#'s async/await but didn't get a macos release. This latest release of netcoredbg has a macos release and will enable support of C#'s async/await on macos correctly. 
I personally only tested on linux, but will test on Window shortly and update the PR when done. I don't personally have a mac so it would be great if someone else could try it out on mac.
> Updated netcoredbg to 1.2.0-761 to enable mac support of async/await

- python3/vimspector/gadgets.py
Fixes issue with netcoredbg sha256sum not matching the actual download's sha256sum on macos
> Update sha256sum of netcoredbg for macos

- docs/configuration.md
A small typo that wastes time for people that copy and modify the config file
> FIx typo in configuration.md

- README.md
- autoload/vimspector.vim
- plugin/vimspector.vim
- python3/vimspector/breakpoints.py
- python3/vimspector/debug_session.py
- python3/vimspector/gadgets.py
- support/test/cpp/simple_c_program/.vimspector.json
- support/test/cpp/simple_c_program/test_c.cpp
- tests/breakpoints.test.vim
- tests/breakpoints_doublewidth.test.vim
- tests/testdata/cpp/simple/.vimspector.json
- tests/ui.test.vim
Log points are added when `logMessage` is in the extra breakpoints options.
These work in codelldb, but in vscode-cpptools it seems that you have to only add them _after_ starting debugging (don't seem to work if added beforehand). So we use codelldb in the tests, which is a good thing to be doing anyway.
> Add support for logpoints

- README.md
- autoload/vimspector.vim
- doc/vimspector-ref.txt
- doc/vimspector.txt
- plugin/vimspector.vim
- python3/vimspector/breakpoints.py
- python3/vimspector/code.py
- python3/vimspector/debug_session.py
- python3/vimspector/settings.py
- python3/vimspector/utils.py
- python3/vimspector/variables.py
- tests/session.test.vim
- update-vim-docs
Manual load/store of:
- breakpoins
- saved "entered data" in the debug session
- watches
We wanted to automate this store/load but it's just really hard to know
when to do it. So we make it a manual operation for save/load specifying
a file name. We can still add something automatic if we can work out the
best way to do that.
Also add VimspectorMkSession and VimspectorLoadSession commands
By default, we use .vimspector.session. Commands complete file name  which is only optional argument.
Closes #453
> Add basic session save/restore functions

- autoload/vimspector/internal/balloon.vim
- autoload/vimspector/internal/state.vim
- compiler/vimspector_test.vim
- plugin/vimspector.vim
- python3/vimspector/debug_session.py
- python3/vimspector/utils.py
- tests/tabpage.test.vim
You can now kill vimspector sesssion by closing the vimspector session
tab, rather than this causing an ugly backtrace
Fixes #454
> Reset when closing the tab

- README.md
- docs/configuration.md
- docs/schema/vimspector.schema.json
- python3/vimspector/debug_session.py
- run_tests
- support/test/multiple_filetypes/.vimspector.json
- support/test/multiple_filetypes/test.js
- support/test/multiple_filetypes/test.py
- tests/get_configurations.test.vim
You can now specify `filetypes` in the `configuration` block as a list of vim filetypes the configuration applies to. When the list is specified for a configuration and no current buffer filetype is in the list, then the configuration is ignored.
This allows for better workflow when you have multiple types of file in your project. You can combine this with the 'default' and 'autoselect' entries to make default configurations for specific filetypes within your project.
Suggestion by @SUPERustam
> Filter configurations by filetype

- README.md
- autoload/vimspector.vim
- autoload/vimspector/internal/balloon.vim
- doc/vimspector.txt
- python3/vimspector/debug_session.py
- python3/vimspector/settings.py
- python3/vimspector/utils.py
- python3/vimspector/variables.py
- support/custom_ui_vimrc
- tests/variables_compact.test.vim
This change removes the "type" from the variables and watches windows, replacing it with a hover popup that contains it. This is particularly useful for certain debug adapters like delve which include lots of repeated/duplicated data about the type of variables for some reason.
This also truncates the value so that we only display the first line of any multi-line values (again, the full value is visible in the hover popup).  Closes #487 (probably)
I'm changing the default here, which might annoy users, so there's an option `g:vimspector_variables_display_mode = 'full'` that restores the old behaviour. I may decide to remove it in future.
> Compact variables UI

- README.md
Fixes a typo in the docs (euro symbol used instead of hash in internal anchor link).
> Fix typo in mappings anchor link.

- README.md
it took me literally 1 day to figure this out why it was not working on 1 of my server :D no errors what so ever just a silent fail, you need to have ```node``` command wokring.
> nodejs is required for php debugging for vscode-php-debug

- python3/vimspector/breakpoints.py
Some servers (like the chrome one) don't populate 'line' in server bp
when not (yet) verified. In those cases, use the user-defined line, but
make sure to use the server-defined verified state.
closes #545
> line may not be set in server breakpoint if unverified

- README.md
- docs/configuration.md
- python3/vimspector/debug_session.py
- python3/vimspector/settings.py
- tests/get_configurations.test.vim
- tests/language_csharp.test.vim
- tests/manual/run
Apparently some people want to do this. Now that we have the 'filetypes'
option in the configuration it does seem reasonable as an alternative to
the g:vimspector_base_dir/configuration/os/language/blah.json which
seems to confuse users quite a lot.
example:
```
let g:vimspector_adapters = #{
\   test_debugpy: #{ extends: 'debugpy' }
\ }
let g:vimspector_configurations = {
\ "test_debugpy_config": {
\   "adapter": "test_debugpy",
\   "filetypes": [ "python" ],
\   "configuration": {
\     "request": "launch",
\     "type": "python",
\     "cwd": "${fileDirname}",
\     "args": [],
\     "program": "${file}",
\     "stopOnEntry": v:false,
\     "console": "integratedTerminal",
\     "integer": 123,
\   },
\   "breakpoints": {
\     "exception": {
\       "raised": "N",
\       "uncaught": …
```
> Allow configuration of via .vimrc

- README.md
It looks like the wiki page for community supported languages was moved from "/wiki/languages" to "/wiki/additional-language-support"
This PR fixes the link in the README to direct to the appropriate page.
> Fix link to additional language support

- python3/vimspector/debug_session.py
From a conversation on gitter:
> As regards this latter nuisance I think it's due to https://github.com/puremourning/vimspector/blob/4c693f33e3038c1199e0f2e1045f340339714b60/python3/vimspector/debug_session.py#L1523
> it's probably this actually: https://github.com/puremourning/vimspector/blob/4c693f33e3038c1199e0f2e1045f340339714b60/python3/vimspector/debug_session.py#L1519
>
> should probably be `reason.splitlines()`
---
This is the first code ever I write in Python. I'm happy to learn what's wrong (or what would be better) with it :smile:
> Fix line formatting of error message

- python3/vimspector/gadgets.py
current version 1.7.3 does not support "env" config item while 1.8.3 does.
> update delve version to 1.8.3

- python3/vimspector/debug_session.py
- support/test/multiple_filetypes/.vimspector.json
- tests/get_configurations.test.vim
- tests/language_csharp.test.vim
This makes it easier for people who don't know about v:true/v:false when
writing config in viml. It might be a trap, though probably not.
Fixes #587
> Allow truthy values for default and autoselect

- README.md
- doc/vimspector-ref.txt
- doc/vimspector.txt
- docs/configuration.md
The previous installation path of `OpenDebugAD7` was deprecated after https://github.com/microsoft/vscode-cpptools/pull/7858/.
Related discussion: https://github.com/puremourning/vimspector/discussions/597
> Update path to `OpenDebugAD7` in docs

- plugin/vimspector.vim
[vim-repeat](https://github.com/tpope/vim-repeat) is a popular Vim plugin that can use "`.`" to repeat `<Plug>`mappings or commands. I think this usage is very suitable for debuggers. 
This PR adds support for vim-repeat for stepping, breakpoint, frame and eval operations, which are usually used continuously during debugging.
> Add support for vim-repeat

- python3/vimspector/utils.py
- tests/python/Test_ExpandReferencesInDict.py
Even though we cannot know if the variable is a file, it doesn't hurt to
have autocompletion for the most common type.
> Add `'file'` autocompletion in AskForInput

- README.md
The old one doesn't exist anymore.
> Fix link to additional languages wiki page

- docs/configuration.md
Fixes syntax errors in the remote C example and uses the jsonc file type
so comments are not shown as errors.
> Fix minor errors in the configuration documentation

- README.md
I think the original guideline is a little bit confusing regarding to the difference between using a Git clone and using plugin managers.
Secondly, I linked the concepts about the .vimspector.json reference guide and the reference to gadgets. Hopefully [issues like this](https://github.com/puremourning/vimspector/issues/621#issuecomment-1181503298) would become less and less.
However, I'm not sure whether ["Check the dependencies"](https://github.com/puremourning/vimspector/blob/0602a20e99b04d90a3ce161a884b1b5522a5006e/README.md?plain=1#L194) is relevant to ["Dependencies" section in README](https://github.com/puremourning/vimspector#dependencies). If this is currect, I will add this to the installation method "Using a plugin manager"
> docs(README): clarify installation methods

- README.md
Just made some small edits to the README to fix some typos!
> docs(README): Fix typos and grammar issues

- run_tests
Measured to save 13.5s on Raspberry Pi 4B - nice when running single short test which takes less than that.
Closes #645
> Add option to skip test programs rebuild

- run_tests
#641 contains an error in `run_tests` `$VERSION_OPTIONS`, which always treats runner as Neovim, even for regular vim
> Fix vim version specific flags

- README.md
Example sets variable `pid`, but then uses `proc_id`
> Fix variable name mismatch in README

- autoload/vimspector.vim
- plugin/vimspector.vim
- I've searched for `vimspector#CompleteOutput` and didn't find other references.
- As [this line](https://github.com/puremourning/vimspector/blob/3378018bc1cdd1d9b70734c3e970bc52fd983415/python3/vimspector/output.py#L60) indicates, `vimspector#CompleteOutput` won't return a list with items not an instance of string; hence nothing will be ignored by `customlist`
- I've tested this by command `:VimspectorShowOutput` **_on Vim 8.2 only, and I don't use neovim_**
I'm thinking of another feature which will be based on this PR, but not related to the title. So I'm concealing below.
<details>
I would like to add a command `VimspectorShowBuffer` which allows one to faster switch faster among all the buffers.
In order to do this, I'm considering making use of `vimspector#CompleteOutput()` and …
> avoid unnecessary string concat

- .github/workflows/build.yaml
- README.md
- compiler/vimspector_test.vim
- dev_requirements.txt
- python3/vimspector/breakpoints.py
- python3/vimspector/debug_session.py
- python3/vimspector/disassembly.py
- python3/vimspector/utils.py
- run_tests
- support/test/cpp/simple_c_program/.vimspector.json
- tests/breakpoints.test.vim
- tests/ci/image/Dockerfile
- tests/disassembly.test.vim
- tests/get_configurations.test.vim
- tests/lib/autoload/vimspector/test/signs.vim
- tests/lib/plugin/shared.vim
- tests/lib/run_test.vim
- tests/testdata/cpp/simple/Makefile
- tests/testdata/cpp/simple/tiny.c
Add support for instruction breakpoints to the disassembly window.
Bit flaky, but work reasonably as a quick win.
We model them as line breakpoints where the file/line point to the disassembly buffer. Then we use the address of the instruction associated with the breakpoint to find the new line whenever the disassembly changes.
> Instruction breakpoints

- python3/vimspector/output.py
This can cause a bad traceback when you have fzf open in a popup-window-terminal, which doesn't allow window switching in vim.
> Avoid switching windows all the time when updating the output buffers

- README.md
- autoload/vimspector/internal/disassembly.vim
- python3/vimspector/debug_session.py
- python3/vimspector/disassembly.py
- python3/vimspector/utils.py
"Infinite" scrolling for the disassembly window.
The way this works is it dumbly requests an extra page when the top line of the window reaches 1, and when its >= buffer length minus 1 page.
We don't trim or anything, so it just grows. It always shrinks the next time we jump to a frame though.
We also drop any request if one is in progress, which is not ideal, but it's simple.
> Disassembly scoll

- doc/vimspector-ref.txt
- docs/configuration.md
- docs/schema/vimspector.schema.json
- python3/vimspector/debug_session.py
This allows one to run commands locally without having to `ssh` to `localhost` which helps when running `vimspector` in a docker container.
> Allow the user to run 'runCommands' locally

- docs/schema/vimspector.schema.json
I was thinking a bit more about the schema change in #699 , and it didn't sit right with me so I tested it and turns out I was wrong.
This example shows a hard error when trying to have both `host` and `container` in the same adapter specification whereas the previous schema allowed it.
```
{
"adapters": {
"with-nothing-specified": {
"extends": "CodeLLDB",
"launch": {
"remote": {
"runCommands": [
[ "echo", "hello" ]
]
}
}
},
"with-host-specified": {
"extends": "CodeLLDB",
"launch": {
"remote": {
"host": "127.0.0.1",
"account": "mark",
"runCommands": [
[ "echo", "hello" ]
]
}
}
},
"with-both-host-and-container-specified": {
"extends": "CodeLLDB",
"launch": {
"remote": {
"host": "127.0.0.1",
"container": "golden_beelzebub",
"account": "mark",
"runCommands": [ [ "echo", "hello" ] ]
}
}
}
}, …
```
> Disallow simultaneous 'host' and 'container'

- python3/vimspector/code.py
This simply does a `zv` after successfully setting cursor in position.
`zv` requires `+folding` to be enabled in Vim, which is one of the features of Vim huge build, and it's a requirement stated in README.
fix #679
> Open fold when jumping to a frame

- python3/vimspector/debug_session.py
Just adds a `-t` to the current `docker exec` command to support outputting colours in the output terminal when debugging code on a docker container
> Add -t to docker exec to support colorful output

- README.md
- autoload/vimspector/internal/neowinbar.vim
- python3/vimspector/code.py
- python3/vimspector/disassembly.py
- python3/vimspector/output.py
- python3/vimspector/settings.py
- python3/vimspector/utils.py
- python3/vimspector/variables.py
- tests/ci/image/Dockerfile
- tests/disassembly.test.vim
- tests/manual/image/Dockerfile
- tests/ui.test.vim
Neovim's winbar uses the statusline syntax with some horrible hack to have it call a function on click. Ugh. So we just do that.
There's also an [annoying bug](https://github.com/neovim/neovim/issues/23165) which means we have to re-render the winbar whenever the buffer changes in a UI window.
Fixes #594
> Neovim: Support winbar

- autoload/vimspector/internal/state.vim
- python3/vimspector/utils.py
> Fix crash when entering a new tab before vimspector is initialised

- README.md
- autoload/vimspector.vim
- autoload/vimspector/internal/neojob.vim
- autoload/vimspector/internal/state.vim
- plugin/vimspector.vim
- python3/vimspector/breakpoints.py
- python3/vimspector/debug_session.py
- python3/vimspector/output.py
- python3/vimspector/session_manager.py
- python3/vimspector/utils.py
- support/minimal_vimrc
- tests/breakpoints.test.vim
- tests/tabpage.test.vim
- tests/temporary_breakpoints.test.vim
- tests/variables.test.vim
- tests/variables_compact.test.vim
This is a bit clunky but works, even for 2 root level sessions which themselves have child sessions.
You have the following facilities:
1. VimspectorNewSession <name> This creates a new session and makes it active. Optional name is used in place of the generated one when starting a launch.
2. Switching to a specific debug tab makes that session active. This is intuitive and probably the most common way to work with this.
3. Switching manually using VimspectorSwitchToSession <tab complete>.
4. vimspector#GetSessionName() useful for putting in a statusline. I used this:
```
function! BenGetCustomInfo()
if !empty( &buftype )
return ''
endif
if !exists( '*vimspector#GetSessionName' )
return ''
endif
return vimspector#GetSessionName()
endfunction
" ... statusline stuff
" Custom info
set …
```
> Support multiple independent root level sessions (tabs)

- python3/vimspector/gadgets.py
The undocumented required arguments:
```
export interface LaunchRequestArguments extends DebugProtocol.LaunchRequestArguments {
// Non-optional arguments are guaranteed to be defined in extension.ts: resolveDebugConfiguration().
argsString: string;
args: string[];
env: object;
cwd: string;
cwdEffective: string;
program: string;
programEffective: string;
pathBash: string;
pathBashdb: string;
pathBashdbLib: string;
pathCat: string;
pathMkfifo: string;
pathPkill: string;
terminalKind?: 'integrated' | 'external' | 'debugConsole';
showDebugOutput?: boolean;
/** enable logging the Debug Adapter Protocol */
trace?: boolean;
}
```
From: https://github.com/rogalmic/vscode-bash-debug/blob/e9ae6ea07c05ce621d2f25b899b5560d000d9c57/src/bashDebug.ts#L17
"Resolved" sadly by client-side-specific code …
> Bash argssstring

- .github/ISSUE_TEMPLATE/bug_report.yml
- reproducable -> reproducible
- "Works in vim?" seems a weird question, considering one is doing a bug report, e.g. it looks like you're asking "does the example to show that something doesn't work, work?"
> Fix some typos in bug issue template

- python3/vimspector/variables.py
We use the connection property of the result when expanding, so we need to update it when we get a new result. Most of the time this will be NOP but in the case of a variable which is carried over from a previous session, it will change the first time we refresh it.
Fixes #789
> Fix expanding variables after restart

- doc/vimspector-ref.txt
- docs/configuration.md
The --disable-randomization argument was spelled the British way, which keeps gdbserver from starting correctly
> documentation: Correct spelling error for gdbserver example

- docs/configuration.md
A couple of trivial docs fixes - add one missing reference and switch from http to https for puremourning.github.io
> Minor docs fixes - missing reference and switch from http to https for puremourning.github.io

- .github/workflows/build.yaml
- CONTRIBUTING.md
- README.md
- autoload/vimspector/internal/channel.vim
- autoload/vimspector/internal/job.vim
- python3/vimspector/debug_session.py
- python3/vimspector/settings.py
- python3/vimspector/variables.py
- python3/vimspector/vendor/json_minify.py
- run_tests
- tests/ci/image/Dockerfile
- tests/lib/autoload/vimspector/test/setup.vim
- tests/lib/autoload/vimspector/test/signs.vim
- tests/lib/plugin/shared.vim
- tests/lib/run_test.vim
- tests/manual/image/Dockerfile
- tests/mappings.test.vim
- tests/memory.test.vim
- tests/tabpage.test.vim
- tests/variables.test.vim
- tests/variables_compact.test.vim
- tests/vimrc
3 people have now asked for this, and I can sort of see why you might want to do it. So you can now disable the mouse balloon feature with g:vimspector_enable_auto_hover=0.
Default remains on, of course.
Closes #496
> Add feature option to disable auto hovering

- README.md
Added a one-liner tutorial to demonstrate that we can achieve source map with CodeLLDB by adding an extra `sourceMap` item in vimspector configuration file. Source Map enables `step-into` functionality for Rust standard library code. 
Specifically, we'll the `sourceMap` item in `configurations` section of the `.vimspector.json`, 
```json
{
"adapters": { // Some configs for adapters },
"configurations": {
"request": "<launch or attach>",
"sourceMap": { "from_path" : "to_path"}
}
} 
```
In Linux, we could also find the `from_path by:
`strings target/debug/<your-binary-name> | grep -o '^/rustc/[^/]\+/' | uniq`
other than using the disassembly window.
> Update README.md for Rust source map in configuration 

- python3/vimspector/gadgets.py
Maybe this will fix CI flakes.
> Update delve to 1.22 for compatibility with latest go

- python3/vimspector/breakpoints.py
Servers can support disassembly without instruction breakpoints.
> Check capabilities before sending instruction breakpoints

- python3/vimspector/debug_session.py
- python3/vimspector/stack_trace.py
- run_tests
- tests/disassembly.test.vim
There was a suspicious TODO in the code, which was the main reason this was broken: We were unconditionally "continuing" all threads when doing StepOver. This is obviously wrong, and it's correct for StepIn, StepOut etc. -> Wait for the step response and only continue the thread that you stepped within.
Meanwhile I also noticed that the 'stopped' event handling was incorrect if we get a flood of stopped events for different threads. If we got 3 stopped events in quick succession, we'd end up dropping the middle one. This was because we only stored the latest-most pending request. Not sure why i thought that was a good idea, as the handler for the stoppped event includes the thread ID that was actully stopped.
This particularly affects the java debugger which is afaict the only one that …
> Fix thread state when stepping over

- README.md
edit makes click able link to take reader to the path specified .  
see Images 
before 
after 
note : 
I made this change because I was going thru the docs and trying out vimspector.  I went to the go example and wished i could have clicked it.  if the comunity merges this change Ill go and fix the rest of the documentatoin
Thanks for making a great tool !
> Eddited MD syntax so there is a clickable link to dir path

- python3/vimspector/core_utils.py
paths on windows are not case-sensitive, and we're not really good about equivalent paths with differing case. However, it would be nice to believe that normpath() deals with that. Which, of course, it doesn't.
For the most part though it works, with the frustrating exception of drive letters. So we hack it to normalise drive letters to uppercase, which prevents duplicate paths appearing in the breakpoints lists.
Fixes #898
> Normalise path letters on Windows

- .github/workflows/build.yaml
- README.md
- python3/vimspector/installer.py
tclParser used by TCLProDebug doesn't compile on TCL 9. While that remains an upstream problem, try to find TCL 8 on macOS to fix CI at least.
> Use TCL8 on macOS in preference

- python3/vimspector/stack_trace.py
- support/test/cpp/simple_c_program/.vimspector.json
Sometimes when stepping by instruction, we get a stack trade with a line of 0. This causes a backtrace in Vim when trying to place a sign on that line. Skip this error.
Fixes #944
> Fix backtrace when CodeLLDB produces a line of 0
