puremourning/vimspector

python3/vimspector/code.py
=> Fix typo in UI

python3/vimspector/debug_session.py
gdbserver has a bug which means that it can't actually attach to running
processes on some versions due to sending signals to the wrong PID (not
the process group leader, or something). The workaround is to manually
send kill -TRAP to the PID in order for the initial break to be
regiseterd.
Doing this manually is painful, so we allow the remote object to run a
command after having successfully initialized the engine, which is about
the time you need to kick the trap/breakpoint.
https://sourceware.org/bugzilla/show_bug.cgi?id=18945
Example:
```
"cpptools-remote-gdb-devtoolset-8": {
"variables": {
"remoteGdbServerPort": 5001,
"devToolsetVersion": 8
},
"name": "cppdbg",
"command": [
"mono",
"--config",
"${gadgetDir}/vscode-cpptools/framework/config.linux", …
```
=> Allow running a command after remote attach

README.md
Removing missing images and a little spell correction.
=> Removing missing images and spell correction

.gitignore, azure-pipelines.yml, make_package
=> Azure release

python3/vimspector/code.py, python3/vimspector/output.py, python3/vimspector/utils.py, python3/vimspector/variables.py, tests/tabpage.test.vim
=> fix tabpage errors

python3/vimspector/utils.py
Allows for variables to reference other variables in the same layer:
```json
+      "variables": [
+        {
+          "python": {
+            "shell": "/bin/bash -c 'if [ -z \"${VIRTUAL_ENV}\" ]; then echo $$(which python); else echo \"${VIRTUAL_ENV}/bin/python\"; fi'"
+          },
+          "nosetests": {
+            "shell": "/bin/bash -c 'if [ -z \"${VIRTUAL_ENV}\" ]; then echo $$(which nosetests); else echo \"${VIRTUAL_ENV}/bin/nosetests\"; fi'"
+          }
+        },
+        {
+          "python_path": {
+            "shell": [
+              "${python}",
+              "${workspaceRoot}/run_tests.py",
+              "--dump-path"
+            ]
+          }
}
```
=> Allow dependent groups of variables in a list

README.md, install_gadget.py, python3/vimspector/breakpoints.py, python3/vimspector/debug_session.py, support/test/go/hello_world/.gitignore, support/test/go/hello_world/.vimspector.json, support/test/go/hello_world/hello-world.go
Experimental for now.
Fixes #48
=> Go support using vscode-go

python3/vimspector/code.py
Fixes #54 
As discussed on #54, we can re-use the terminal window if the terminal within it has completed. This makes the common use-case of restarting debugging involve fewer irritating dead terminals in increasingly narrow vsplits.
cc: @doronbehar
=> RunInTermal: Re-use a completed terminal

autoload/vimspector/internal/channel.vim, install_gadget.py, python3/vimspector/breakpoints.py, python3/vimspector/debug_session.py
There seems to be a bug attaching to processes using vscode-python. But we can connect directly to ptvsd using a socket. This improves socket connections somewhat, by waiting longer (allowing the user more time to start up ptvsd manually)
=> Python ptvsd

README.md, python3/vimspector/breakpoints.py, python3/vimspector/code.py, python3/vimspector/utils.py
=> Add customisation of signs

README.md, docs/configuration.md
This is useful enough to be made public. Closes #97.
=> Document LaunchWithSettings

README.md
=> Spell correction on README

README.md, support/test/python/simple_python/.vimspector.json
=> Document how to use debugpy directly instead of vscode-python

python3/vimspector/stack_trace.py, python3/vimspector/utils.py, python3/vimspector/variables.py
This makes the UI feel more like a UI.
=> Set some window options to their deafults

python3/vimspector/utils.py
Support splat for variable expansion in lists.
The motivating example for this is to allow shell arguments to be specified like:
```json
"program" : "/path/to/a/script",
"args": [ "arg1", "*${args}", "arg2" ]
```
or some similar. We want to ask the user for some command line arguments, but:
* (optionally) we want to supply our own args before or after them (or both)
* we _must_ supply the args as a list
=> List splat

python3/vimspector/code.py, python3/vimspector/debug_session.py
=> Set the code window to the current buffer

README.md, azure-pipelines.yml, run_tests, tests/testdata/cpp/simple/.vimspector.json
Thanks to @neiljohari  for updating cpptools. This change removes all of the workarounds we had in place.
=> Remove workaround for broken cpptools

CONTRIBUTING.md, README.md, make_package
Also make sure that the gadget installer and other docs are included in
the tarball installation.
cc @dboeckenhoff who pointed out that install_gadget.py was missing from the tarball installation!
=> Add troubleshooting guide

install_gadget.py
Nice improvement to the variables window
=> Update debugpy to v1.0.0b8

python3/vimspector/stack_trace.py
=> Make sure we can still request threads if one threads request fails

.vimspector.json, azure-pipelines.yml, compiler/vimspector_test.vim, python3/vimspector/breakpoints.py, python3/vimspector/debug_session.py, python3/vimspector/developer.py, tests/breakpoints.test.vim, tests/lib/run_test.vim
=> Fix listing breakpoints while debugging

docs/configuration.md, docs/schema/vimspector.schema.json, python3/vimspector/debug_session.py
adds a second method of connection during an attach session via `docker exec -it`
=> add docker exec as an attach command

python3/vimspector/utils.py
cc @adam-r-kowalski - does this fix it for you?
=> Fix traceback in neovim: vim.vars returns str

README.md, docs/configuration.md, install_gadget.py, python3/vimspector/debug_session.py, python3/vimspector/utils.py, python3/vimspector/variables.py
=> Automatically pick a local port for CodeLLDB

install_gadget.py
Added windows config for netcoredbg
=> Added Windows support for C# debugging

python3/vimspector/output.py, tests/lib/autoload/vimspector/test/signs.vim, tests/variables.test.vim
=> Put the cursor at the end of the buffer after evaluations

README.md, autoload/vimspector.vim, python3/vimspector/installer.py, python3/vimspector/settings.py, python3/vimspector/utils.py
Useful for storing config in source control
=> Allow a statically configured list of gadgets

support/custom_ui_vimrc, tests/ui.test.vim
Add an example to show symbol and mapping on WinBar:
UI test result:
=> Custom text of Winbar buttons.

CONTRIBUTING.md, README.md, autoload/vimspector.vim, plugin/vimspector.vim, python3/vimspector/debug_session.py, python3/vimspector/output.py
This ls useful to just grab the Vimjspector log and can be used even when Vimspector session is not running.
=> Add VimspectorToggleLog

.vimspector.json, python3/vimspector/installer.py
=> Fix installation issues on windows - find npm.cmd

README.md, python3/vimspector/stack_trace.py, python3/vimspector/variables.py
=> Add double-click to expand/collapse

python3/vimspector/breakpoints.py, python3/vimspector/code.py, support/test/python/multiple_files/.vimspector.json, support/test/python/multiple_files/cow.py, support/test/python/multiple_files/moo.py, tests/breakpoints.test.vim, tests/breakpoints_doublewidth.test.vim, tests/lib/autoload/vimspector/test/signs.vim
Fixes #267 
I should really add a test for this :/
=> While debugging, use the correct path for breakpoints

README.md, autoload/vimspector.vim, python3/vimspector/debug_session.py, tests/get_configurations.test.vim
=> Add a GetConfigurations function

.github/workflows/build.yaml, python3/vimspector/variables.py, tests/variables.test.vim
Rather than just getting into a weird state.
=> Print failure when watch expression errors

README.md, install_gadget.py, python3/vimspector/gadgets.py, python3/vimspector/installer.py
=> multiple languages per adapter

README.md, plugin/vimspector.vim, python3/vimspector/code.py, python3/vimspector/debug_session.py, python3/vimspector/utils.py, support/custom_ui_vimrc, tests/ui.test.vim
This is almost entirely the work of @przepompownia (dziękuje bardzo!) and closes #343 .
I have only added some docs and changed the test to cover it a bit more clearly.
=> Add User autocommands when jumping to frame and resetting

autoload/vimspector/internal/channel.vim
Fix restarts always getting stuck "Initializing" when using CodeLLDB.
When using the restart command we re-use the configuration dict as-is,
so always re-use the same TCP port for the lldb socket. Originally it
was thought this was due to a race condition, having the port still
open, but it's not.
When doing a restart, or reset, we shut down the server after we get the
response to the disconnect message. CodeLLDB then also sends a
'terminated' message.
Previously we were forcefully closing the socket before killing the app,
after we get the 'disconnect' response. This meant that the OS buffer
for the socket to localhost:<the port> still contained the terminated
message at the point that we force-closed the socket and killed the
server.
The result was that the firt messages read from the …
=> Fix restart when using CodeLLDB

python3/vimspector/output.py
it's not like anyone will ever look at it
=> hide the pointless telemetry data;

autoload/vimspector.vim, python3/vimspector/debug_session.py
=> Delay launching the python interpreter until needed

autoload/vimspector.vim, tests/mappings.test.vim
Add at least a basic test for this!
Fixes #365
=> Fix crash using Stop function

README.md, autoload/vimspector.vim, autoload/vimspector/internal/balloon.vim, autoload/vimspector/internal/neopopup.vim, autoload/vimspector/internal/popup.vim, plugin/vimspector.vim, python3/vimspector/custom/java.py, python3/vimspector/debug_adapter_connection.py, python3/vimspector/debug_session.py, python3/vimspector/gadgets.py, python3/vimspector/settings.py, python3/vimspector/utils.py, support/test/java/test_project/pom.xml
Closes #252 
This adds some fancy UI too.
=> Hot code replace for java

.github/ISSUE_TEMPLATE/bug_report.md, README.md, autoload/vimspector.vim, plugin/vimspector.vim, python3/vimspector/debug_session.py, python3/vimspector/output.py
Fixes #399 
This is just the simplest thing right now. We can add more stuff to it over time.
=> Add basic VimspectorDebugInfo command

support/custom_ui_vimrc
=> Fix error: E806: using Float as a String.

python3/vimspector/gadgets.py, python3/vimspector/installer.py, tests/testdata/cpp/simple/.vimspector.json, tests/variables.test.vim
Only tested on linux as i don't have any other.
The "newly" introduced _bin_ sub directory was there on windows all the time so i hope this works on osx too.
=> Update vscode-cpptools from 0.27.0 to 1.6.0

README.md
That took me way too long as vscode-cpptools documentation shoves you in a rabbit hole with *natvis* and what not.
=> Readme: pretty printing with vscode-cpptools / gdb

python3/vimspector/installer.py
=> Fix cpptools install on winders

python3/vimspector/gadgets.py
https://github.com/xdebug/vscode-php-debug/releases/tag/v1.21.1
=> Upgrade vscode-php-debug to 1.21.1

python3/vimspector/gadgets.py
https://github.com/xdebug/vscode-php-debug/releases/tag/v1.22.0
=> Upgrade vscode-php-debug to 1.22.0

doc/vimspector.txt
Update the vim docs after recent changes
=> [Auto] Update vim docs

README.md, autoload/vimspector.vim, doc/vimspector.txt, python3/vimspector/code.py, python3/vimspector/debug_session.py, python3/vimspector/settings.py, python3/vimspector/stack_trace.py, python3/vimspector/utils.py, python3/vimspector/variables.py, python3/vimspector/vendor/hexdump.py, syntax/vimspector-memory.vim, tests/language_go.test.vim, tests/lib/plugin/shared.vim, tests/memory.test.vim
Add support for reading memory and dumping an xxd-like output.
Demo:
https://asciinema.org/a/6zGMcHVnvQAPyMsBSWZrSQiHL
Fixes https://github.com/puremourning/vimspector/issues/498
=> Memory Dump

python3/vimspector/gadgets.py
See https://github.com/xdebug/vscode-php-debug/releases/tag/v1.23.0
=> Update vscode-php-debug to 1.23.0

python3/vimspector/gadgets.py
https://github.com/xdebug/vscode-php-debug/releases/tag/v1.24.1
https://github.com/xdebug/vscode-php-debug/releases/tag/v1.24.0
=> Upgrade vscode-php-debug to 1.24.1

python3/vimspector/gadgets.py
https://github.com/xdebug/vscode-php-debug/releases/tag/v1.24.2
=> Upgrade vscode-php-debug to 1.24.2

python3/vimspector/gadgets.py
https://github.com/xdebug/vscode-php-debug/releases/tag/v1.25.0
=> Update vscode-php-debug to 1.25.0

autoload/vimspector.vim
=> Work around vim bug with v:null; use exists() instead

README.md, autoload/vimspector.vim, plugin/vimspector.vim, python3/vimspector/debug_session.py, python3/vimspector/utils.py, tests/goto.test.vim
If there's one target on the line, jump to it. If there are multiple,
ask the user from a list. If there are none, print a message.
Simples.
Closes #161
=> Support for GoToTargets/GoTo

python3/vimspector/breakpoints.py, python3/vimspector/debug_session.py, python3/vimspector/terminal.py, python3/vimspector/utils.py
Make sure to dance around assigning vim var dict members
Fixes #565
=> Work around neovim python

python3/vimspector/gadgets.py, python3/vimspector/installer.py, python3/vimspector/stack_trace.py, run_tests, support/gadget_upgrade/README.md, support/gadget_upgrade/download_and_checksum_gadget.py, tests/manual/image/.vim/vimrc, tests/manual/run, tests/testdata/cpp/simple/.vimspector.json, tests/testdata/cpp/simple/Makefile
=> Update vscode-cpptools to v1.9.7

README.md, autoload/vimspector.vim, plugin/vimspector.vim, python3/vimspector/breakpoints.py, python3/vimspector/debug_session.py, tests/breakpoints.test.vim
Tested automatically on vim and NeoVim using the written test methods.
Half of #633, will add `JumpToPC` in separate PR to keep them small (less implementation, more tests as need to let PC move about).
=> Add JumpToNext/PreviousBreakpoint

README.md, autoload/vimspector.vim, plugin/vimspector.vim, python3/vimspector/debug_session.py, python3/vimspector/stack_trace.py, tests/stack_trace.test.vim
=> Add JumpToProgramCounter

.github/workflows/build.yaml, .mergify.yml, run_tests, tests/breakpoints.test.vim, tests/breakpoints_doublewidth.test.vim, tests/ci/image/Dockerfile, tests/get_configurations.test.vim, tests/language_csharp.test.vim, tests/language_go.test.vim, tests/language_python.test.vim, tests/lib/plugin/shared.vim, tests/mappings.test.vim, tests/memory.test.vim, tests/session.test.vim, tests/stack_trace.test.vim, tests/tabpage.test.vim, tests/temporary_breakpoints.test.vim, tests/ui.test.vim, tests/utils.test.vim, tests/variables.test.vim, tests/variables_compact.test.vim
=> Skip tests failing on NeoVim

python3/vimspector/breakpoints.py, tests/breakpoints.test.vim, tests/lib/autoload/vimspector/test/signs.vim
=> Fix finding breakpoints when moved by server

.github/workflows/build.yaml, python3/vimspector/gadgets.py, run_tests, support/test/python/simple_python/.vimspector.json, support/test_python3.vim
=> Fix legacy python2 adapter

.github/workflows/build.yaml, python3/vimspector/breakpoints.py, tests/breakpoints.test.vim
=> Fix leaking buffers when showing breakpoints window

python3/vimspector/breakpoints.py, python3/vimspector/code.py, python3/vimspector/utils.py, syntax/vimspector-breakpoints.vim, tests/breakpoints.test.vim
Show the value of a line breakpoint's current line in the breakpoints window
=> Breakpionts window line value

.github/workflows/build.yaml, autoload/vimspector/internal/neopopup.vim, autoload/vimspector/internal/popup.vim, python3/vimspector/utils.py, tests/lib/autoload/vimspector/test/signs.vim
=> Fix leaking buffers when hiding the splash screen

README.md
Supplement missing backquotes.
=> Update README.md (Supplement missing backquotes)

python3/vimspector/breakpoints.py, python3/vimspector/stack_trace.py
=> Minor fixes

python3/vimspector/breakpoints.py, python3/vimspector/debug_session.py, tests/breakpoints.test.vim
=> Fix showing breakpoints when connection closed

README.md, autoload/vimspector.vim, python3/vimspector/breakpoints.py, python3/vimspector/debug_session.py, python3/vimspector/settings.py, support/test/python/simple_python/.vimspector.json, tests/breakpoints.test.vim
…inbar in neovim
Fixes #299 
Fixes #737
=> Allow editing of breakpoint options in breakpoints window

.github/workflows/build.yaml, .mergify.yml, python3/vimspector/variables.py, tests/variables.test.vim
Fixes #837 
@cridemichel can you verify this fixes it for you?
=> Fix traceback when adding a watch without current frame

README.md, docs/configuration.md, docs/schema/index.md
Fixed various spelling errors using a spellchecker plugin
=> Fix spelling errors in docs
